name: Auto Update FanCode playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # প্রতি ১৫ মিনিটে run

permissions:
  contents: write

jobs:
  secure-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Unzip Python Script (AES256)
        run: |
          7z x FanCode_sm.zip -p"${{ secrets.ZIP_PASSWORD }}" -y

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        run: |
          python fancode_sm.py

      - name: Cleanup
        run: |
          rm -f fancode_sm.py

      - name: Commit & Push Output Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # চেক করুন কোনো ফাইল আপডেট হয়েছে কি না
          if [[ -n $(git status -s) ]]; then
            git add fancode_bd.m3u fancode_in.m3u FanCode_data.json
            git commit -m "Auto Update FanCode - $(date +'%Y-%m-%d %H:%M:%S')"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi
